<?php if (!defined('APPLICATION')) exit();
/** This file was generated by the Locale Developer plugin on 2010-11-23 12:22:01 **/


$Definition['%s and you'] = '%s နှင့် သင်';
$Definition['%s comment'] = '%s ဆွေးနွေးချက်';
$Definition['%s comments'] = '%s ဆွေးနွေးချက်';
$Definition['%s Connect'] = '%s ချိတ်ဆက်သည်';
$Definition['%s message'] = '%s စာ';
$Definition['%s New'] = '%s ခု အသစ်';
$Definition['%s new'] = '%s ခု အသစ်';
$Definition['%s New Plural'] = '%s ခု အသစ်';

$Definition['1 message'] = 'စာ ၁ စောင် ရှိ';

$Definition['About'] = 'အချက်အလက်';
$Definition['Accepted'] = 'လက်ခံသည်';
$Definition['Activity'] = 'လှုပ်ရှားမှု';
$Definition['Activity.AboutUpdate.FullHeadline'] = '%1$s updated %6$s profile.';
$Definition['Activity.AboutUpdate.ProfileHeadline'] = '%1$s updated %6$s profile.';
$Definition['Activity.ActivityComment.FullHeadline'] = '%1$s commented on %4$s %8$s.';
$Definition['Activity.ActivityComment.ProfileHeadline'] = '%1$s';
$Definition['Activity.AddedToConversation.FullHeadline'] = '%1$s added you to a %8$s.';
$Definition['Activity.AddedToConversation.ProfileHeadline'] = '%1$s added  you to a %8$s.';
$Definition['Activity.BookmarkComment.FullHeadline'] = '%1$s commented on your %8$s.';
$Definition['Activity.BookmarkComment.ProfileHeadline'] = '%1$s commented on your %8$s.';
$Definition['Activity.Comment'] = 'Comment';
$Definition['Activity.CommentMention.FullHeadline'] = '%1$s mentioned %3$s in a %8$s.';
$Definition['Activity.CommentMention.ProfileHeadline'] = '%1$s mentioned %3$s in a %8$s.';
$Definition['Activity.ConversationMessage.FullHeadline'] = '%1$s sent you a %8$s.';
$Definition['Activity.ConversationMessage.ProfileHeadline'] = '%1$s sent you a %8$s.';
$Definition['Activity.DiscussionComment.FullHeadline'] = '%1$s commented on %4$s %8$s.';
$Definition['Activity.DiscussionComment.ProfileHeadline'] = '%1$s commented on %4$s %8$s.';
$Definition['Activity.DiscussionMention.FullHeadline'] = '%1$s mentioned %3$s in a %8$s.';
$Definition['Activity.DiscussionMention.ProfileHeadline'] = '%1$s mentioned %3$s in a %8$s.';
$Definition['Activity.Import.FullHeadline'] = '%1$s သည် အချက်အလက်များ ထည့်သွင်းပြီး';
$Definition['Activity.Import.ProfileHeadline'] = '%1$s imported data.';
$Definition['Activity.Join.FullHeadline'] = '%1$s joined.';
$Definition['Activity.Join.ProfileHeadline'] = '%1$s joined.';
$Definition['Activity.JoinApproved.FullHeadline'] = '%1$s approved %4$s membership application.';
$Definition['Activity.JoinApproved.ProfileHeadline'] = '%1$s approved %4$s membership application.';
$Definition['Activity.JoinCreated.FullHeadline'] = '%3$s created an account for %1$s.';
$Definition['Activity.JoinCreated.ProfileHeadline'] = '%3$s created an account for %1$s.';
$Definition['Activity.JoinInvite.FullHeadline'] = '%1$s accepted %4$s invitation for membership.';
$Definition['Activity.JoinInvite.ProfileHeadline'] = '%1$s accepted %4$s invitation for membership.';
$Definition['Activity.NewDiscussion.FullHeadline'] = '%1$s သည် <strong>%8$s</strong> တွင် စတင်ရေးသားလိုက်သည်';
$Definition['Activity.NewDiscussion.ProfileHeadline'] = '%1$s started a %8$s.';
$Definition['Activity.PictureChange.FullHeadline'] = '%1$s ၏ ရုပ်ပုံ ပြောင်းလဲလိုက်သည်။';
$Definition['Activity.PictureChange.ProfileHeadline'] = '%1$s changed %6$s profile picture.';
$Definition['Activity.RoleChange.FullHeadline'] = '%1$s changed %4$s permissions.';
$Definition['Activity.RoleChange.ProfileHeadline'] = '%1$s changed %4$s permissions.';
$Definition['Activity.SignIn.FullHeadline'] = '%1$s signed in.';
$Definition['Activity.SignIn.ProfileHeadline'] = '%1$s signed in.';
$Definition['Activity.WallComment.FullHeadline'] = '%1$s wrote on %4$s %5$s.';
$Definition['Activity.WallComment.ProfileHeadline'] = '%1$s wrote:';
$Definition['Add'] = 'ထည့်ရန်';
$Definition['Add Comment'] = 'ဆွေးနွေးချက် တင်ရန်';
$Definition['Add Info &amp; Create Account'] = 'အချက်အလက် ဖြည့်စွက်ရန် နှင့် ​account ဖန်တီးရန်';
$Definition['Add Message'] = 'စာထည့်ရန်';
$Definition['Add People to this Conversation'] = 'ယခု သီးသန့်စာတွင် လူအသစ်ထည့်ရန်';
$Definition['All Conversations'] = 'သီးသန့်စာ အကုန်';
$Definition['All Discussions'] = 'ပြောဆို ဆွေးနွေးခြင်းများ';
$Definition['Allow other members to see your email?'] = 'အခြားသူများကို သင့်ရဲ့ email ကြည့်ရှုခွင့် ပေးမလား ?';
$Definition['Announce'] = 'ကြေငြာချက်';
$Definition['Applicants'] = 'Applicants';
$Definition['Apply'] = 'အသုံးပြုမည်';
$Definition['Apply for Membership'] = 'အဖွဲ့ဝင် အဖြင့် လျှောက်ထားခြင်း';
$Definition['Are you sure you want to do that?'] = 'ဒါလုပ်မှာ သေချာလား?';
$Definition['at'] = 'at';

$Definition['Back to Discussions'] = '​ေဆွးနွေးခြင်းများသို့ ပြန်သွားရန်';
$Definition['Bookmark'] = 'Bookmark';
$Definition['bookmarked discussion'] = 'မှတ်ထားတဲ့ ဆွေးနွေးချက်';
$Definition['Bookmarked Discussions'] = 'မှတ်ထားတဲ့ ဆွေးနွေးချက်များ';
$Definition['By uploading a file you certify that you have the right to distribute this picture and that it does not violate the Terms of Service.'] = 'By uploading a file you certify that you have the right to distribute this picture and that it does not violate the Terms of Service.';

$Definition['Cancel'] = 'လက်မခံ';
$Definition['Categories'] = 'အမျိုးအစားများ';
$Definition['Category'] = 'အမျိုးအစား';
$Definition['Change My Password'] = 'လျို့ဝှက်စာလုံး ပြောင်းလဲမည်';
$Definition['Change My Picture'] = 'ရုပ်ပုံ ပြောင်းလဲမည်';
$Definition['Close'] = 'ပိတ်သည်';
$Definition['comment'] = 'ထင်မြင်ချက်';
$Definition['Comment'] = 'ထင်မြင်ချက်';
$Definition['Confirm'] = 'သေချာသည်';
$Definition['Confirm Password'] = 'လျို့ဝှက်စာလုံး ပြန်ထည့်ရန်';
$Definition['Connect'] = 'ချိတ်ဆက်သည်';
$Definition['conversation'] = 'သီးသန့်စာ';
$Definition['Conversations'] = 'သီးသန့်စာများ';
$Definition['Create One.'] = 'တစ်ခုဖန်တီးရန်';

$Definition['Dashboard'] = 'ပင်မထိန်းချုပ်နေရာ';
$Definition['Date.DefaultDayFormat'] = '%B %e';
$Definition['Date.DefaultFormat'] = '%B %e, %Y';
$Definition['Date.DefaultTimeFormat'] = '%l:%M%p';
$Definition['Date.DefaultYearFormat'] = '%B %Y';
$Definition['Delete'] = 'ဖျက်သည်';
$Definition['Delete Account'] = 'Account ဖျက်သည်';
$Definition['Delete Conversation'] = 'ယခု သီးသန့်စာကို ဖျက်ရန်';
$Definition['Delete Discussion'] = 'ဆွေးနွေးချက်ကို ဖျက်ရန်';
$Definition['discussion'] = 'ဆွေးနွေးချက်';
$Definition['Discussion Title'] = 'ဆွေးနွေးသည့် ခေါင်းစဉ်';
$Definition['Discussions'] = 'ဆွေးနွေးချက်များ';
$Definition['Don\'t have an account? %s'] = 'Account မရှိဘူးလား ? %s';
$Definition['dot'] = 'dot';
$Definition['Drag around and resize the square below to define your thumbnail icon.'] = 'Drag around and resize the square below to define your thumbnail icon.';

$Definition['Edit'] = 'ပြင်ရန်';
$Definition['Edit Account'] = 'Account ပြင်ရန်';
$Definition['Edit My Account'] = 'ကျွနု်ပ် Account ပြင်ရန်';
$Definition['Edit My Thumbnail'] = 'ရုပ်ပုံပြင်ဆင်ရန်';
$Definition['Edit Preferences'] = 'စိတ်ကြိုက်ပြင်ဆင်ရန်';
$Definition['Email'] = 'Email';
$Definition['Email Notifications'] = 'Email ဖြင့် အကြောင်းကြားခြင်း';
$Definition['Email Unavailable'] = 'email အသုံးပြုလို့ မရပါ';
$Definition['EmailInvitation'] = 'Hello!

%1$s has invited you to join %2$s. If you want to join, you can do so by clicking this link:

  %3$s

Have a great day!';
$Definition['EmailMembershipApproved'] = 'Hello %1$s,

You have been approved for membership. Sign in now at the following link:

  %2$s
  
Have a great day!';
$Definition['EmailNotification'] = '%1$s

Follow the link below to check it out:
%2$s

Have a great day!';
$Definition['EmailPassword'] = 'Hello %1$s,

%2$s has reset your password at %3$s. Your login credentials are now:

  Email: %6$s
  Password: %5$s
  Url: %4$s

Have a great day!';
$Definition['EmailStoryNotification'] = '%1$s

%3$s

---
Follow the link below to check it out:
%2$s

Have a great day!';
$Definition['EmailWelcome'] = 'Hello %1$s,

%2$s has created an account for you at %3$s. Your login credentials are:

  Email: %6$s
  Password: %5$s
  Url: %4$s

Have a great day!';
$Definition['EmailWelcomeConnect'] = 'Hello {User.Name},

You have successfully connected to {Title}. Here is your information:

  Username: {User.Name}
  Connected With: {ProviderName}

You can access the site at {/,url,domain}.

Have a great day!';
$Definition['EmailWelcomeRegister'] = 'Hello {User.Name},

You have successfully registered for an account at {Title}. Here is your information:

  Username: {User.Name}
  Email: {User.Email}

You can access the site at {/,url,domain}.

Have a great day!';
$Definition['Enter the email address of the person you would like to invite:'] = 'Enter the email address of the person you would like to invite:';
$Definition['Enter your Email address'] = 'Enter your Email address';
$Definition['Enter your existing account password.'] = 'Enter your existing account password.';
$Definition['ErrorCredentials'] = 'Sorry, no account could be found related to the email and password you entered.';
$Definition['ErrorPermission'] = 'သင့်အား ဝင်ခွင့်မပြုပေ ။';
$Definition['ErrorRecordNotFound'] = 'The requested record could not be found.';
$Definition['ErrorTermsOfService'] = 'You must agree to the terms of service.';

$Definition['Female'] = 'မိန်းကလေး';
$Definition['Forgot?'] = 'မေ့နေလား?';

$Definition['Gender'] = 'ကျား ၊ မ';
$Definition['GenderSuffix.First.f'] = '';
$Definition['GenderSuffix.First.m'] = '';
$Definition['GenderSuffix.Third.f'] = '';
$Definition['GenderSuffix.Third.m'] = '';
$Definition['Go'] = 'Go';
$Definition['GuestModule.Message'] = 'ကြိုဆိုပါတယ်။ အခုမှ ပထမဆုံး အကြိမ် ရောက်ဖူးတာလား ? ဝင်ရောက် ဆွေးနွေး မေးမြန်းလိုလျှင် အောက်မှာ ရှိတဲ့ button တွေကနေ တဆင့် ဝင်ရောက် ဆွေးနွေးနိုင်သလို အဖွဲ့ ဝင် အသစ်အနေနဲ့လည်း လျှောက်ထားနိုင်ပါတယ်။ ';

$Definition['he'] = 'သူ';
$Definition['her'] = 'သူမ၏';
$Definition['his'] = 'သူ၏';
$Definition['Howdy, Stranger!'] = 'မင်္ဂလာပါ!';

$Definition['I agree to the <a id="TermsOfService" class="Popup" target="terms" href="%s">terms of service</a>'] = 'I agree to the <a id="TermsOfService" class="Popup" target="terms" href="%s">terms of service</a>';
$Definition['I remember now!'] = 'I remember now!';
$Definition['In this Conversation'] = 'ဒီ သီးသန့်စာထဲတွင်';
$Definition['Inbox'] = 'စာတိုက်';
$Definition['Internal'] = 'Internal';
$Definition['Invitation Code'] = 'Invitation Code';
$Definition['Invite'] = 'Invite';
$Definition['Invited by'] = 'Invited by';

$Definition['Joined'] = 'စသည့် နေ့';

$Definition['Keep me signed in'] = 'အမြဲဝင်ထားရန်';

$Definition['Last Active'] = 'နောက်ဆုံး ဝင်ချိန်';
$Definition['Login with Facebook'] = 'Facebook ဖြင့်ဝင်ရန်';

$Definition['Male'] = 'ယောက်ျားလေး';
$Definition['Most recent by %1$s'] = 'နောက်ဆုံးရေးသားသူ %1$s';
$Definition['My Bookmarks'] = 'ကျွနု်ပ် မှတ်ထားမှု';
$Definition['My Discussions'] = 'ကျွနု်ပ်၏ ဆွေးနွေးချက်များ';
$Definition['My Drafts'] = 'ကျွနု်ပ်၏ စာကြမ်း';
$Definition['My Invitations'] = 'ကျွနု်ပ်၏ ဖိတ်ကြားမှုများ';
$Definition['My Preferences'] = 'ကျွန်ုပ်၏ စိတ်ကြိုက် ပြင်ဆင်မှု';

$Definition['Name Unavailable'] = 'Name Unavailable';
$Definition['No discussions were found.'] = 'ဆွေးနွေးချက်များ ရှာမတွေ့ပါ';
$Definition['Notifications'] = 'အချက်ပေး ချက်များ';
$Definition['Notify me of private messages.'] = 'စာရောက်နေရလျှင် အချက်ပေးပါ';
$Definition['Notify me when I am added to private conversations.'] = 'Notify me when I am added to private conversations.';
$Definition['Notify me when people comment on my bookmarked discussions.'] = 'Notify me when people comment on my bookmarked discussions.';
$Definition['Notify me when people comment on my discussions.'] = 'Notify me when people comment on my discussions.';
$Definition['Notify me when people mention me in comments.'] = 'Notify me when people mention me in comments.';
$Definition['Notify me when people mention me in discussion titles.'] = 'Notify me when people mention me in discussion titles.';
$Definition['Notify me when people reply to my wall comments.'] = 'ကွန်ုပ် wall မှာ အခြားသူတွေ ဆွေးနွေးချက်ကို အကြောင်းပြန်ရင် ကွန်ုပ်ကို အချက်ပေးပါ';
$Definition['Notify me when people write on my wall.'] = 'ကွန်ုပ် wall မှာ အခြားသူတွေ လာရေးရင် ကွန်ုပ်ကို အချက်ပေးပါ';

$Definition['Okay'] = 'ကောင်းပြီ';
$Definition['On'] = 'On';
$Definition['Options'] = 'Options';
$Definition['Or you can...'] = 'Or you can...';
$Definition['Original'] = 'Original';

$Definition['PageDetailsMessage'] = '%1$s to %2$s';
$Definition['PageDetailsMessageFull'] = '%1$s to %2$s of %3$s';
$Definition['Password'] = 'Password';
$Definition['PasswordRequest'] = 'Hello %1$s,

Someone has requested to reset your password at %2$s. To reset your password, follow this link:

  %3$s

If you did not make this request, disregard this email.';
$Definition['Passwords don\'t match'] = 'Passwords don\'t match';
$Definition['Permalink'] = 'Permalink';
$Definition['Please wait while you are redirected. If you are not redirected, click <a href="%s">here</a>.'] = 'Please wait while you are redirected. If you are not redirected, click <a href="%s">here</a>.';
$Definition['Post Comment'] = 'ထင်မြင်ချက် တင်သည်';
$Definition['Post Discussion'] = 'ဆွေးနွေးချက် တင်သည်';
$Definition['Powered by Vanilla'] = 'Powered by Vanilla';
$Definition['Preview'] = 'နမူနာ';
$Definition['Profile Picture'] = 'Profile Picture';

$Definition['Recent Activity'] = 'ပြီးခဲ့တဲ့ လှုပ်ရှားမှုတွေ';
$Definition['Recipients'] = 'Recipients';
$Definition['Redirecting...'] = 'Redirecting...';
$Definition['Remember me on this computer'] = 'Remember me on this computer';
$Definition['Remove My Picture'] = 'ကွန်ုပ်ပုံကို ဖြုတ်လိုက်ပါ';
$Definition['Request a new password'] = 'လျို့ဝှက်စာလုံး အသစ် တောင်းရန်';
$Definition['Roles'] = 'ကဏ္ဍ';

$Definition['Save'] = 'သိမ်းရန်';
$Definition['Save Draft'] = 'စာကြမ်း သိမ်းရန်';
$Definition['Save Preferences'] = 'Save Preferences';
$Definition['Search'] = 'Search';
$Definition['Select an image on your computer (2mb max)'] = 'Select an image on your computer (2mb max)';
$Definition['Send %s a Message'] = 'Send %s a Message';
$Definition['Send Message'] = 'စာပို့ရန်';
$Definition['Sent To'] = 'သို့';
$Definition['Share'] = 'Share';
$Definition['she'] = 'she';
$Definition['Sign In'] = 'ဝင်ရန်';
$Definition['Sign In with Google'] = 'Google ဖြင့် ဝင်ရန်';
$Definition['Sign In with OpenID'] = 'OpenID ဖြင့် ဝင်ရန်';
$Definition['Sign In with Twitter'] = 'Twitter ဖြင့်ဝင်ရန်';
$Definition['Sign Out'] = 'ထွက်ရန်';
$Definition['Sign Up'] = 'Sign Up';
$Definition['Sink'] = 'Sink';
$Definition['somebody'] = 'somebody';
$Definition['Start a New Conversation'] = 'သီးသန့်စာ အသစ် ရေးရန်';
$Definition['Start a New Discussion'] = 'မေးမြန်း ၊ ဆွေးနွေး မှုစတင်ရန်';
$Definition['Start Conversation'] = 'Start Conversation';
$Definition['Started by %1$s'] = 'Started by %1$s';
$Definition['Status'] = 'Status';

$Definition['Thank You!'] = 'ကျေးဇူးတင်ပါတယ်!';
$Definition['Thumbnail'] = 'Thumbnail';
$Definition['Transport error: %s'] = 'A fatal error occurred while processing the request.<br />The server returned the following response: %s';

$Definition['Unbookmark'] = 'Unbookmark';
$Definition['Upload'] = 'Upload';
$Definition['Username'] = 'အသုံးပြုသူ နာမည်';

$Definition['ValidateBoolean'] = '%s is not a valid boolean.';
$Definition['ValidateConnection'] = 'The connection parameters you specified failed to open a connection to the database. The database reported the following error: <code>%s</code>';
$Definition['ValidateDate'] = '%s is not a valid date.';
$Definition['ValidateDecimal'] = '%s is not a valid decimal.';
$Definition['ValidateEmail'] = '%s does not appear to be valid.';
$Definition['ValidateEnum'] = '%s is not valid.';
$Definition['ValidateInteger'] = '%s is not a valid integer.';
$Definition['ValidateLength'] = '%1$s is %2$s characters too long.';
$Definition['ValidateMatch'] = 'The %s fields do not match.';
$Definition['ValidateMinimumAge'] = 'You must be at least 16 years old to proceed.';
$Definition['ValidateOneOrMoreArrayItemRequired'] = 'You must select at least one %s.';
$Definition['ValidateRegex'] = '%s does not appear to be in the correct format.';
$Definition['ValidateRequired'] = '%s is required.';
$Definition['ValidateRequiredArray'] = 'You must select at least one %s.';
$Definition['ValidateTime'] = '%s is not a valid time.';
$Definition['ValidateTimestamp'] = '%s is not a valid timestamp.';
$Definition['ValidateUsername'] = 'Usernames must be 3-20 characters and consist of letters, numbers, and underscores.';
$Definition['ValidateVersion'] = 'The %s field is not a valid version number. See the php version_compare() function for examples of valid version numbers.';
$Definition['Visits'] = 'ကြည့်ရှုမှုပေါင်း';

$Definition['wall'] = 'wall';
$Definition['Why do you want to join?'] = 'Why do you want to join?';
$Definition['Write a comment'] = 'Write a comment';
$Definition['Write Comment'] = 'Write Comment';
$Definition['Write something about yourself...'] = 'Write something about yourself...';

$Definition['you'] = 'သင်';
$Definition['You'] = 'သင်';
$Definition['You already have an account here.'] = 'သင်၏ ​account ရှိပြီးသားဖြစ်သည်။';
$Definition['You are connected as %s through %s.'] = 'You are connected as %s through %s.';
$Definition['You do not have any conversations.'] = 'You do not have any conversations.';
$Definition['You do not have any notifications yet.'] = 'You do not have any notifications yet.';
$Definition['your'] = 'your';
$Definition['Your application will be reviewed by an administrator. You will be notified by email if your application is approved.'] = 'Your application will be reviewed by an administrator. You will be notified by email if your application is approved.';
$Definition['Your registered username: <strong>%s</strong>'] = 'Your registered username: <strong>%s</strong>';
$Definition['Popular']='လူကြည့်အများဆုံး';
$Definition['Popular Tags']='အသုံးများသည့် Tags';
$Definition['Votes']='ထောက်ခံမှု';
$Definition['Views']='ကြည့်ရှုမှု';