<?php if (!defined('APPLICATION')) exit();
/** This file was generated by the Locale Developer plugin on 2010-11-23 12:23:07 **/

$LocaleInfo['Baseline'] = array (
  'Locale' => 'my-My',
  'Name' => 'Myanmarsar',
  'Description' => 'Myanmar Lanauge',
  'Version' => '1.0',
  'Author' => 'saturngod',
  'AuthorEmail' => 'saturngod@gmail.com',
  'AuthorUrl' => 'http://www.saturngod.net',
  'License' => 'GPL2',
);

