<?php if (!defined('APPLICATION')) exit();
/** This file was generated by the Locale Developer plugin on 2010-11-23 12:23:07 **/

$LocaleInfo['my-MM'] = array (
  'Locale' => 'my-MM',
  'Name' => 'မြန်မာစာ',
  'Description' => 'Myanmar Lanauge , မြန်မာ ဘာသာစကား',
  'Version' => '0.2',
  'Author' => 'saturngod',
  'AuthorEmail' => 'saturngod@gmail.com',
  'AuthorUrl' => 'http://www.saturngod.net',
  'License' => 'GPL2',
);

/*******
ADMIN
********/

$Definition['%1$s on %2$s'] = '%1$s on %2$s';
$Definition['%1$s Version %2$s'] = '%1$s Version %2$s';
$Definition['%s user(s) found.'] = 'အဖွဲ့ဝင် %s ယောက် ရှိသည်';

$Definition['(YYYY-mm-dd)'] = '(YYYY-mm-dd)';

$Definition['1 month after being sent'] = '၁လကြာပြီးနောက်';
$Definition['1 week after being sent'] = '၁ပတ်ကြာပြီးနောက်';

$Definition['2 weeks after being sent'] = '၂ပတ်ကြပြီးနောက်';

$Definition['<General Error>'] = '<General Error>';
$Definition['<strong>%1$s</strong> (%2$s) %3$s'] = '<strong>%1$s</strong> (%2$s) %3$s';
$Definition['<strong>The basic registration form requires</strong> that new users copy text from a "Captcha" image to keep spammers out of the site. You need an account at <a href="http://recaptcha.net/">recaptcha.net</a>. Signing up is FREE and easy. Once you have signed up, come back here and enter the following settings:'] = '<strong>The basic registration form requires</strong> that new users copy text from a "Captcha" image to keep spammers out of the site. You need an account at <a href="http://recaptcha.net/">recaptcha.net</a>. Signing up is FREE and easy. Once you have signed up, come back here and enter the following settings:';

$Definition['[%1$s] Membership Approved'] = '[%1$s] အဖွဲ့ဝင်အဖြစ် အသိအမှတ်ပြုသည်။';

$Definition['_Locale'] = 'Locale';

$Definition['A url-friendly version of the category name for better SEO.'] = 'A url-friendly version of the category name for better SEO.';
$Definition['Action'] = 'ပြုလုပ်ချက်';
$Definition['Activate'] = 'Activate';
$Definition['Add'] = 'ထည့်သည်';
$Definition['Add Message'] = 'စာထည့်ရန်';
$Definition['Add Route'] = 'Add Route';
$Definition['Add User'] = 'အဖွဲ့ဝင်အသစ်ထည့်ရန်';
$Definition['Addons'] = 'Addons';
$Definition['Administrator'] = 'စီမံခန့်ခွဲသူ';
$Definition['Advanced'] = 'ထပ်မံ ပြုပြင်ခြင်း';
$Definition['Advanced Forum Settings'] = 'Advanced Forum Settings';
$Definition['All <span>16</span>'] = 'All <span>16</span>';
$Definition['All <span>2</span>'] = 'All <span>2</span>';
$Definition['Announce'] = 'ကြေငြာချက်';
$Definition['Appearance'] = 'အသွင်အပြင်';
$Definition['Applicant'] = 'Applicant';
$Definition['Applicants'] = 'Applicants';
$Definition['Application'] = 'Application';
$Definition['Application ID'] = 'Application ID';
$Definition['Application Secret'] = 'Application Secret';
$Definition['ApplicationHelp'] = 'Applications allow you to add large groups of functionality to your site.<br />Once an application has been added to your %s folder, you can enable or disable it here.';
$Definition['Applications'] = 'Applications';
$Definition['Approve'] = 'Approve';
$Definition['Archive Discussions'] = 'Archive Discussions';
$Definition['Are you sure you want to do that?'] = 'Are you sure you want to do that?';
$Definition['at'] = 'at';
$Definition['Authentication'] = 'Authentication';

$Definition['Banned'] = 'Banned';
$Definition['Banner'] = 'Banner';
$Definition['Banner Logo'] = 'Banner Logo';
$Definition['Banner Title'] = 'Banner Title';

$Definition['Cancel'] = 'Cancel';
$Definition['Capture locale pack changes.'] = 'Capture the changes between one of your locale packs and the Locale Developer. It will be put in the <code>changes.php</code> file.';
$Definition['Categories'] = 'အမျိုးအစားများ';
$Definition['Categories are used to help organize discussions. '] = 'Categories are used to help organize discussions. ';
$Definition['Category'] = 'အမျိုးအစား';
$Definition['Category Url:'] = 'Category Url:';
$Definition['Change the way that new users register with the site.'] = 'Change the way that new users register with the site.';
$Definition['Check all permissions that apply for each role'] = 'Check all permissions that apply for each role';
$Definition['Check all roles that apply to this user:'] = 'Check all roles that apply to this user:';
$Definition['Choose a locale pack'] = 'Choose a locale pack';
$Definition['Choose and configure your forum\'s authentication scheme.'] = 'Choose and configure your forum\'s authentication scheme.';
$Definition['Choose who can send out invitations to new members:'] = 'Choose who can send out invitations to new members:';
$Definition['Close'] = 'ပိတ်သည်';
$Definition['comment(s)'] = 'မှတ်ချက်';
$Definition['Comments'] = 'မှတ်ချက်များ';
$Definition['Comments per Page'] = 'စာတစ်မျက်နှာတွင် မှတ်ချက် အရေအတွက်';
$Definition['Configure an Authenticator'] = 'Configure an Authenticator';
$Definition['Confirm'] = 'Confirm';
$Definition['Confirm Email'] = 'Confirm Email';
$Definition['Consumer Key'] = 'Consumer Key';
$Definition['Consumer Secret'] = 'Consumer Secret';
$Definition['Conversation Messages'] = 'Conversation Messages';
$Definition['Conversations'] = 'သီးသန့်စာများ';
$Definition['Copy'] = 'Copy';
$Definition['Copy locale pack.'] = 'Copy the definitions from a locale pack to the Locale Developer. The definitions will be put in the <code>copied.php</code> file.';
$Definition['Current Authenticator'] = 'Current Authenticator';
$Definition['Current Theme'] = 'Current Theme';
$Definition['Customize your Public Profile'] = 'Customize your Public Profile';

$Definition['Date.DefaultDayFormat'] = '%B %e';
$Definition['Date.DefaultTimeFormat'] = '%l:%M%p';
$Definition['Decline'] = 'Decline';
$Definition['Delete'] = 'Delete';
$Definition['Description'] = 'Description';
$Definition['Disable'] = 'Disable';
$Definition['Disable Google Sign In'] = 'Disable Google Sign In';
$Definition['Disable OpenID'] = 'Disable OpenID';
$Definition['Disabled <span>0</span>'] = 'Disabled <span>0</span>';
$Definition['Disabled <span>10</span>'] = 'Disabled <span>10</span>';
$Definition['Disabled <span>11</span>'] = 'Disabled <span>11</span>';
$Definition['Disabled <span>12</span>'] = 'Disabled <span>12</span>';
$Definition['Disabled <span>9</span>'] = 'Disabled <span>9</span>';
$Definition['Discussion & Comment Editing'] = 'Discussion & Comment Editing';
$Definition['discussion(s)'] = 'ဆွေးနွေးချက်';
$Definition['Discussions'] = 'ဆွေးနွေးချက်များ';
$Definition['Discussions per Page'] = 'Discussions per Page';
$Definition['dot'] = 'dot';

$Definition['Edit'] = 'Edit';
$Definition['edit'] = 'edit';
$Definition['Edit Category'] = 'Edit Category';
$Definition['Edit User'] = 'Edit User';
$Definition['EditContentTimeout.Notes'] = 'Note: If a user is in a role that has permission to edit content, those permissions will override any value selected here.';
$Definition['Email'] = 'Email';
$Definition['Email sent from the application will be addressed from the following name and address'] = 'Email sent from the application will be addressed from the following name and address';
$Definition['Email visible to other users'] = 'Email visible to other users';
$Definition['EmailMembershipApproved'] = 'Hello %1$s,

You have been approved for membership. Sign in now at the following link:

  %2$s
  
Have a great day!';
$Definition['Enable'] = 'Enable';
$Definition['Enable Google Sign In'] = 'Enable Google Sign In';
$Definition['Enable OpenID'] = 'Enable OpenID';
$Definition['Enabled <span>2</span>'] = 'Enabled <span>2</span>';
$Definition['Enabled <span>4</span>'] = 'Enabled <span>4</span>';
$Definition['Enabled <span>5</span>'] = 'Enabled <span>5</span>';
$Definition['Enabled <span>6</span>'] = 'Enabled <span>6</span>';
$Definition['Enabled <span>7</span>'] = 'Enabled <span>7</span>';
$Definition['Existing members send invitations to new members.'] = 'Existing members send invitations to new members.';

$Definition['Facebook Connect allows users to sign in using their Facebook account.'] = 'Facebook Connect allows users to sign in using their Facebook account. <b>You must register your application with Facebook for this plugin to work.</b>';
$Definition['Facebook Settings'] = 'Facebook Settings';
$Definition['First Visit'] = 'First Visit';
$Definition['For more help on localization check out the page <a href="%s">here</a>.'] = 'For more help on localization check out the page <a href="%s">here</a>.';
$Definition['Forum Settings'] = 'Forum Settings';

$Definition['Garden.Email.SupportAddress'] = 'Support email';
$Definition['Garden.Import.Description'] = 'Use this page to import data from another forum that was exported using Vanilla\'s exporter. For more information <a href="%s">see our importing documentation</a>.';
$Definition['Garden.Import.InputInstructions'] = 'Enter the email and password of the admin user from the data being imported.';
$Definition['Garden.Import.Overwrite.Description'] = 'Warning: All data in this forum will be overwritten.';
$Definition['Generate'] = 'Generate';
$Definition['Generate Password'] = 'Generate Password';
$Definition['Go'] = 'Go';
$Definition['Google Sign In Settings'] = 'Google Sign In Settings';
$Definition['Guest'] = 'Guest';

$Definition['here'] = 'here';

$Definition['Import'] = 'Import';
$Definition['Information'] = 'Information';
$Definition['Internal'] = 'Internal';
$Definition['Invitations can be sent from users\' profile pages.'] = 'When you use registration by invitation users will have a link called <a href="%s" class="Popup">My Invitations</a> on their profile pages.';
$Definition['Invitations per month'] = 'Invitations per month';
$Definition['Invitations will expire'] = 'Invitations will expire';
$Definition['It is a good idea to keep the maximum number of characters allowed in a comment down to a reasonable size.'] = 'It is a good idea to keep the maximum number of characters allowed in a comment down to a reasonable size.';

$Definition['Key Type'] = 'Key Type';
$Definition['Key Value'] = 'Key Value';

$Definition['Last Visit'] = 'Last Visit';
$Definition['Locale Developer'] = 'Locale Developer';
$Definition['Locale Developer Settings %s.'] = 'Locale Developer Settings %s.';
$Definition['Locale info file settings.'] = '<p>When you generate the zip file you can set the information for the locale below.</p> <p>You can download a zip of the locale pack by clicking <a href="%s">here</a>.</p>';
$Definition['Locale Key (Folder)'] = 'Locale Key (Folder)';
$Definition['Locale Name'] = 'Locale Name';
$Definition['Locales'] = 'Locales';
$Definition['Locales are in your %s folder.'] = 'Locales allow you to support other languages on your site. Once an locale has been added to your %s folder, you can enable or disable it here.';
$Definition['Location'] = 'Location';

$Definition['Manage Applicants'] = 'Manage Applicants';
$Definition['Manage Applications'] = 'Manage Applications';
$Definition['Manage Categories'] = 'Manage Categories';
$Definition['Manage Messages'] = 'Manage Messages';
$Definition['Manage Plugins'] = 'Manage Plugins';
$Definition['Manage Roles & Permissions'] = 'Manage Roles & Permissions';
$Definition['Manage Routes'] = 'Manage Routes';
$Definition['Manage Spam'] = 'Manage Spam';
$Definition['Manage Themes'] = 'Manage Themes';
$Definition['Manage Users'] = 'Manage Users';
$Definition['Manage your Plugins'] = 'Manage your Plugins';
$Definition['Max Comment Length'] = 'Max Comment Length';
$Definition['Member'] = 'အဖွဲ့ဝင်';
$Definition['Message'] = 'Message';
$Definition['Messages'] = 'Messages';
$Definition['Messages can appear anywhere in your application.'] = 'Messages can appear anywhere in your application, and can be used to inform your users of news and events. Use this page to re-organize your messages by dragging them up or down.';
$Definition['Method'] = 'Method';
$Definition['minute(s)'] = 'minute(s)';
$Definition['Moderator'] = 'Moderator';

$Definition['Name'] = 'Name';
$Definition['never'] = 'never';
$Definition['New comments in the last day'] = 'New comments in the last day';
$Definition['New comments in the last week'] = 'New comments in the last week';
$Definition['New conversations in the last day'] = 'New conversations in the last day';
$Definition['New conversations in the last week'] = 'New conversations in the last week';
$Definition['New discussions in the last day'] = 'New discussions in the last day';
$Definition['New discussions in the last week'] = 'New discussions in the last week';
$Definition['New messages in the last day'] = 'New messages in the last day';
$Definition['New messages in the last week'] = 'New messages in the last week';
$Definition['New Password'] = 'New Password';
$Definition['New users are reviewed and approved by an administrator (that\'s you!).'] = 'New users are reviewed and approved by an administrator (that\'s you!).';
$Definition['New users fill out a simple form and are granted access immediately.'] = 'New users fill out a simple form and are granted access immediately.';
$Definition['New users in the last day'] = 'New users in the last day';
$Definition['New users in the last week'] = 'New users in the last week';
$Definition['None'] = 'None';
$Definition['Not Authorized (401)'] = 'Not Authorized (401)';
$Definition['Not Found (404)'] = 'Not Found (404)';

$Definition['OK'] = 'OK';
$Definition['Okay'] = 'Okay';
$Definition['Only Allow Each User To Post'] = 'Only Allow Each User To Post';
$Definition['OpenID Settings'] = 'OpenID Settings';
$Definition['Options'] = 'Options';
$Definition['Or Spamblock For'] = 'Or Spamblock For';
$Definition['Organize your Categories'] = 'Organize your Categories';
$Definition['Other Themes'] = 'Other Themes';
$Definition['Outgoing Email'] = 'Outgoing Email';

$Definition['Page'] = 'Page';
$Definition['Panel Box'] = 'Panel Box';
$Definition['Password'] = 'Password';
$Definition['Password Options'] = 'Password Options';
$Definition['Permanent (301)'] = 'Permanent (301)';
$Definition['Please choose an authenticator to configure.'] = 'Please choose an authenticator to configure.';
$Definition['Plugin'] = 'Plugin';
$Definition['PluginHelp'] = 'Plugins allow you to add functionality to your site.<br />Once a plugin has been added to your %s folder, you can enable or disable it here.';
$Definition['Plugins'] = 'Plugins';
$Definition['Position'] = 'Position';
$Definition['Prevent spam on your forum by limiting the number of discussions &amp; comments that users can post within a given period of time.'] = 'Prevent spam on your forum by limiting the number of discussions &amp; comments that users can post within a given period of time.';
$Definition['Private Key'] = 'Private Key';
$Definition['Public Key'] = 'Public Key';

$Definition['Recently Active Users'] = 'Recently Active Users';
$Definition['Refresh Comments'] = 'Refresh Comments';
$Definition['Registration'] = 'Registration';
$Definition['Remove'] = 'Remove';
$Definition['Remove locale developer files.'] = 'Remove the locale deveoper files and reset your changes.';
$Definition['Requires: '] = 'Requires: ';
$Definition['Reset Password'] = 'Reset Password';
$Definition['Reset password and send email notification to user'] = 'Reset password and send email notification to user';
$Definition['Reveal Password'] = 'Reveal Password';
$Definition['Role'] = 'Role';
$Definition['Roles & Permissions'] = 'Roles & Permissions';
$Definition['Roles determine user\'s permissions.'] = 'Every user in your site is assigned to at least one role. Roles are used to determine what the users are allowed to do.';
$Definition['Route'] = 'Route';
$Definition['Route Expression'] = 'Route Expression';
$Definition['Routes'] = 'Routes';
$Definition['Routes can be used to redirect users to various parts of your site depending on the url.'] = 'Routes can be used to redirect users to various parts of your site depending on the url.';

$Definition['Save'] = 'Save';
$Definition['Search'] = 'Search';
$Definition['seconds'] = 'seconds';
$Definition['Select the file to import'] = 'Select the file to import';
$Definition['Settings'] = 'Settings';

$Definition['Sink'] = 'Sink';
$Definition['SMTP Host'] = 'SMTP Host';
$Definition['SMTP Password'] = 'SMTP Password';
$Definition['SMTP Port'] = 'SMTP Port';
$Definition['SMTP Security'] = 'SMTP Security';
$Definition['SMTP User'] = 'SMTP User';
$Definition['Spam'] = 'Spam';
$Definition['Start your First Discussion'] = 'Start your First Discussion';

$Definition['Target'] = 'Target';
$Definition['Temporary (302)'] = 'Temporary (302)';
$Definition['The %s Authenticator does not have any custom configuration options.'] = 'The %s Authenticator does not have any custom configuration options.';
$Definition['The addon could not be enabled because it generated a fatal error: <pre>%s</pre>'] = 'The addon could not be enabled because it generated a fatal error: <pre>%s</pre>';
$Definition['The banner logo appears at the top of your forum.'] = 'The banner logo appears at the top of your forum.';
$Definition['The banner title appears on the top-left of every page. If a banner logo is uploaded, it will replace the banner title on user-facing forum pages.'] = 'The banner title appears on the top-left of every page. If a banner logo is uploaded, it will replace the banner title on user-facing forum pages.';
$Definition['The file failed to upload.'] = 'The file failed to upload.';
$Definition['ThemeHelp'] = 'Themes allow you to change the look &amp; feel of your site.<br />Once a theme has been added to your %s folder, you can enable it here.';
$Definition['Themes'] = 'Themes';
$Definition['There are currently no applicants.'] = 'There are currently no applicants.';
$Definition['This plugin allows users to sign in with OpenID. <b>Make sure you click Settings after enabling this plugin to enable OpenID signin</b>.'] = 'This plugin allows users to sign in with OpenID. <b>Make sure you click Settings after enabling this plugin to enable OpenID signin</b>.';
$Definition['This plugin allows users to sign in with their Google accounts. <b>Make sure you click Settings after enabling this plugin to enable Google signin</b>.'] = 'This plugin allows users to sign in with their Google accounts. <b>Make sure you click Settings after enabling this plugin to enable Google signin</b>.';
$Definition['This plugin helps locale package development.'] = 'This plugin helps locale package development. The plugin keeps a working locale pack at <code>%s</code>.';
$Definition['Tools'] = 'Tools';
$Definition['Transport error: %s'] = 'A fatal error occurred while processing the request.<br />The server returned the following response: %s';
$Definition['Twitter Connect allows users to sign in using their Twitter account.'] = 'Twitter Connect allows users to sign in using their Twitter account. <b>You must register your application with Twitter for this plugin to work.</b>';
$Definition['Twitter Settings'] = 'Twitter Settings';
$Definition['Type'] = 'Type';

$Definition['Unlimited'] = 'Unlimited';
$Definition['Upload'] = 'Upload';
$Definition['Url'] = 'Url';
$Definition['User'] = 'User';
$Definition['User Registration Settings'] = 'User Registration Settings';
$Definition['Username'] = 'Username';
$Definition['Users'] = 'Users';

$Definition['ValidateRequired'] = '%s is required.';
$Definition['Vanilla.Archive.Description'] = 'You can choose to archive forum discussions older than a certain date. Archived discussions are effectively closed, allowing no new posts.';
$Definition['Version'] = 'Version';
$Definition['Version %s'] = 'Version %s';
$Definition['version %s'] = 'version %s';
$Definition['View'] = 'View';
$Definition['Visit Site'] = 'Visit Site';

$Definition['Warning'] = 'Warning';
$Definition['We will attempt to use the local mail server to send email by default. If you want to use a separate SMTP mail server, you can configure it below.'] = 'We will attempt to use the local mail server to send email by default. If you want to use a separate SMTP mail server, you can configure it below.';
$Definition['Welcome Aboard!'] = 'မင်္ဂလာပါ!';
$Definition['What\'s the Buzz?'] = 'What\'s the Buzz?';
$Definition['Within'] = 'Within';

$Definition['You can always use your password at<a href="%1$s">%1$s</a>.'] = 'If you are ever locked out of your forum you can always log in using your original Vanilla email and password at <a href="%1$s">%1$s</a>';
$Definition['You can place files in your /uploads folder.'] = 'If your file is too

		large to upload directly to this page you can place it in your /uploads

		folder. Make sure the filename begins with the word <b>export</b> and ends

		with one of <b>.txt, .gz</b>.';
$Definition['You cannot disable the %1$s plugin because the %2$s plugin requires it in order to function.'] = 'You cannot disable the %1$s plugin because the %2$s plugin requires it in order to function.';
$Definition['You cannot disable the OpenID plugin because the GoogleSignIn plugin requires it in order to function.'] = 'You cannot disable the OpenID plugin because the GoogleSignIn plugin requires it in order to function.';
$Definition['Your changes have been saved.'] = 'Your changes have been saved.';
$Definition['Your settings have been saved.'] = 'Your settings have been saved.';

/********
END ADMIN
**********/

/*******
user
*********/
$Definition['%s and you'] = '%s နှင့် သင်';
$Definition['%s comment'] = '%s မှတ်ချက်';
$Definition['%s comments'] = '%s မှတ်ချက်များ';
$Definition['%s Connect'] = '%s ချိတ်ဆက်သည်';
$Definition['%s message'] = '%s စာ';
$Definition['%s New'] = '%s ခု အသစ်';
$Definition['%s new'] = '%s ခု အသစ်';
$Definition['%s New Plural'] = '%s ခု အသစ်';

$Definition['1 message'] = 'စာ ၁ စောင် ရှိ';

$Definition['About'] = 'အချက်အလက်';
$Definition['Accepted'] = 'လက်ခံသည်';
$Definition['Activity'] = 'လှုပ်ရှားမှု';
$Definition['Activity.AboutUpdate.FullHeadline'] = '%1$s updated %6$s profile.';
$Definition['Activity.AboutUpdate.ProfileHeadline'] = '%1$s updated %6$s profile.';
$Definition['Activity.ActivityComment.FullHeadline'] = '%1$s commented on %4$s %8$s.';
$Definition['Activity.ActivityComment.ProfileHeadline'] = '%1$s';
$Definition['Activity.AddedToConversation.FullHeadline'] = '%1$s added you to a %8$s.';
$Definition['Activity.AddedToConversation.ProfileHeadline'] = '%1$s added  you to a %8$s.';
$Definition['Activity.BookmarkComment.FullHeadline'] = '%1$s သည် သင်၏ %8$s တွင် မှတ်ချက်ရေးသွားသည်။';
$Definition['Activity.BookmarkComment.ProfileHeadline'] = '%1$s သည် သင်၏ %8$s တွင် မှတ်ချက် ရေးသွားသည်။';
$Definition['Activity.Comment'] = 'Comment';
$Definition['Activity.CommentMention.FullHeadline'] = '%1$s သည် %3$s အား %8$s တွင် ရည်ညွှန်း ရေးသားထားသည်။';
$Definition['Activity.CommentMention.ProfileHeadline'] = '%1$s သည် %3$s အား %8$s တွင် ရည်ညွှန်း ရေးသားထားသည်။';
$Definition['Activity.ConversationMessage.FullHeadline'] = '%1$s သည် %8$s ပို့လိုက်သည်';
$Definition['Activity.ConversationMessage.ProfileHeadline'] = '%1$s သည် %8$s ပို့လိုက်သည်';
$Definition['Activity.DiscussionComment.FullHeadline'] = '%1$s သည် %4$s %8$s တွင် မှတ်ချက်ပေးခဲ့သည်။';
$Definition['Activity.DiscussionComment.ProfileHeadline'] = '%1$s သည် %4$s %8$s တွင် မှတ်ချက်ပေးခဲ့သည်။';
$Definition['Activity.DiscussionMention.FullHeadline'] = '%1$s mentioned %3$s in a %8$s.';
$Definition['Activity.DiscussionMention.ProfileHeadline'] = '%1$s mentioned %3$s in a %8$s.';
$Definition['Activity.Import.FullHeadline'] = '%1$s သည် အချက်အလက်များ ထည့်သွင်းပြီး';
$Definition['Activity.Import.ProfileHeadline'] = '%1$s imported data.';
$Definition['Activity.Join.FullHeadline'] = '%1$s ဝင်ရောက်လာသည်။';
$Definition['Activity.Join.ProfileHeadline'] = '%1$s ဝင်ရောက်လာသည်။';
$Definition['Activity.JoinApproved.FullHeadline'] = '%1$s approved %4$s membership application.';
$Definition['Activity.JoinApproved.ProfileHeadline'] = '%1$s approved %4$s membership application.';
$Definition['Activity.JoinCreated.FullHeadline'] = '%3$s created an account for %1$s.';
$Definition['Activity.JoinCreated.ProfileHeadline'] = '%3$s created an account for %1$s.';
$Definition['Activity.JoinInvite.FullHeadline'] = '%1$s accepted %4$s invitation for membership.';
$Definition['Activity.JoinInvite.ProfileHeadline'] = '%1$s accepted %4$s invitation for membership.';
$Definition['Activity.NewDiscussion.FullHeadline'] = '%1$s သည် <strong>%8$s</strong> တွင် စတင်ရေးသားလိုက်သည်';
$Definition['Activity.NewDiscussion.ProfileHeadline'] = '%1$s started a %8$s.';
$Definition['Activity.PictureChange.FullHeadline'] = '%1$s ၏ ရုပ်ပုံ ပြောင်းလဲလိုက်သည်';
$Definition['Activity.PictureChange.ProfileHeadline'] = '%1$s changed %6$s profile picture.';
$Definition['Activity.RoleChange.FullHeadline'] = '%1$s changed %4$s permissions.';
$Definition['Activity.RoleChange.ProfileHeadline'] = '%1$s changed %4$s permissions.';
$Definition['Activity.SignIn.FullHeadline'] = '%1$s signed in.';
$Definition['Activity.SignIn.ProfileHeadline'] = '%1$s signed in.';
$Definition['Activity.WallComment.FullHeadline'] = '%1$s wrote on %4$s %5$s.';
$Definition['Activity.WallComment.ProfileHeadline'] = '%1$s wrote:';
$Definition['Add'] = 'ထည့်ရန်';
$Definition['Add Comment'] = 'မှတ်ချက် တင်ရန်';
$Definition['Add Info &amp; Create Account'] = 'အချက်အလက် ဖြည့်စွက်ရန် နှင့် ​account ဖန်တီးရန်';
$Definition['Add Message'] = 'စာထည့်ရန်';
$Definition['Add People to this Conversation'] = 'ယခု သီးသန့်စာတွင် လူအသစ်ထည့်ရန်';
$Definition['All Conversations'] = 'သီးသန့်စာ အကုန်';
$Definition['All Discussions'] = 'ပြောဆို ဆွေးနွေးခြင်းများ';
$Definition['Allow other members to see your email?'] = 'အခြားသူများကို သင့်ရဲ့ email ကြည့်ရှုခွင့် ပေးမလား ?';
$Definition['Announce'] = 'ကြေငြာချက်';
$Definition['Announcement'] = 'ကြေငြာချက်';
$Definition['Closed'] = '​ပိတ်ထား​သည်';
$Definition['Applicants'] = 'Applicants';
$Definition['Apply'] = 'အသုံးပြုမည်';
$Definition['Apply for Membership'] = 'အဖွဲ့ဝင် အဖြင့် လျှောက်ထားခြင်း';
$Definition['Are you sure you want to do that?'] = 'ဒါလုပ်မှာ သေချာလား?';
$Definition['at'] = 'at';

$Definition['Back to Discussions'] = '​ေဆွးနွေးခြင်းများသို့ ပြန်သွားရန်';
$Definition['Bookmark'] = 'Bookmark';
$Definition['bookmarked discussion'] = 'မှတ်ထားတဲ့ ဆွေးနွေးချက်';
$Definition['Bookmarked Discussions'] = 'မှတ်ထားတဲ့ ဆွေးနွေးချက်များ';
$Definition['By uploading a file you certify that you have the right to distribute this picture and that it does not violate the Terms of Service.'] = 'By uploading a file you certify that you have the right to distribute this picture and that it does not violate the Terms of Service.';

$Definition['Cancel'] = 'လက်မခံ';
$Definition['Categories'] = 'အမျိုးအစားများ';
$Definition['Category'] = 'အမျိုးအစား';
$Definition['Change My Password'] = 'လျို့ဝှက်စာလုံး ပြောင်းလဲမည်';
$Definition['Change My Picture'] = 'ရုပ်ပုံ ပြောင်းလဲမည်';
$Definition['Close'] = 'ပိတ်သည်';
$Definition['comment'] = 'မှတ်ချက်';
$Definition['Comment'] = 'မှတ်ချက်';
$Definition['Confirm'] = 'သေချာသည်';
$Definition['Confirm Password'] = 'လျို့ဝှက်စာလုံး ပြန်ထည့်ရန်';
$Definition['Connect'] = 'ချိတ်ဆက်သည်';
$Definition['conversation'] = 'သီးသန့်စာ';
$Definition['Conversations'] = 'သီးသန့်စာများ';
$Definition['Create One.'] = 'တစ်ခုဖန်တီးရန်';

$Definition['Dashboard'] = 'ထိန်းချုပ်နေရာ';
$Definition['Date.DefaultDayFormat'] = '%B %e';
$Definition['Date.DefaultFormat'] = '%B %e, %Y';
$Definition['Date.DefaultTimeFormat'] = '%l:%M%p';
$Definition['Date.DefaultYearFormat'] = '%B %Y';
$Definition['Delete'] = 'ဖျက်သည်';
$Definition['Delete Account'] = 'Account ဖျက်သည်';
$Definition['Delete Conversation'] = 'ယခု သီးသန့်စာကို ဖျက်ရန်';
$Definition['Delete Discussion'] = 'ဆွေးနွေးချက်ကို ဖျက်ရန်';
$Definition['discussion'] = 'ဆွေးနွေးချက်';
$Definition['Discussion Title'] = 'ဆွေးနွေးသည့် ခေါင်းစဉ်';
$Definition['Discussions'] = 'ဆွေးနွေးချက်များ';
$Definition['Don\'t have an account? %s'] = 'Account မရှိဘူးလား ? %s';
$Definition['dot'] = 'dot';
$Definition['Drag around and resize the square below to define your thumbnail icon.'] = 'Drag around and resize the square below to define your thumbnail icon.';

$Definition['Edit'] = 'ပြင်ရန်';
$Definition['Edit Account'] = 'Account ပြင်ရန်';
$Definition['Edit My Account'] = 'ကျွနု်ပ် Account ပြင်ရန်';
$Definition['Edit My Thumbnail'] = 'ရုပ်ပုံပြင်ဆင်ရန်';
$Definition['Edit Preferences'] = 'စိတ်ကြိုက်ပြင်ဆင်ရန်';
$Definition['Email'] = 'Email';
$Definition['Email Notifications'] = 'Email ဖြင့် အကြောင်းကြားခြင်း';
$Definition['Email Unavailable'] = 'email အသုံးပြုလို့ မရပါ';
$Definition['EmailInvitation'] = 'Hello!

%1$s has invited you to join %2$s. If you want to join, you can do so by clicking this link:

  %3$s

Have a great day!';
$Definition['EmailMembershipApproved'] = 'Hello %1$s,

You have been approved for membership. Sign in now at the following link:

  %2$s
  
Have a great day!';
$Definition['EmailNotification'] = '%1$s

Follow the link below to check it out:
%2$s

Have a great day!';
$Definition['EmailPassword'] = 'Hello %1$s,

%2$s has reset your password at %3$s. Your login credentials are now:

  Email: %6$s
  Password: %5$s
  Url: %4$s

Have a great day!';
$Definition['EmailStoryNotification'] = '%1$s

%3$s

---
Follow the link below to check it out:
%2$s

Have a great day!';
$Definition['EmailWelcome'] = 'Hello %1$s,

%2$s has created an account for you at %3$s. Your login credentials are:

  Email: %6$s
  Password: %5$s
  Url: %4$s

Have a great day!';
$Definition['EmailWelcomeConnect'] = 'Hello {User.Name},

You have successfully connected to {Title}. Here is your information:

  Username: {User.Name}
  Connected With: {ProviderName}

You can access the site at {/,url,domain}.

Have a great day!';
$Definition['EmailWelcomeRegister'] = 'Hello {User.Name},

You have successfully registered for an account at {Title}. Here is your information:

  Username: {User.Name}
  Email: {User.Email}

You can access the site at {/,url,domain}.

Have a great day!';
$Definition['Enter the email address of the person you would like to invite:'] = 'Enter the email address of the person you would like to invite:';
$Definition['Enter your Email address'] = 'Enter your Email address';
$Definition['Enter your existing account password.'] = 'Enter your existing account password.';
$Definition['ErrorCredentials'] = 'Sorry, no account could be found related to the email and password you entered.';
$Definition['ErrorPermission'] = 'သင့်အား ဝင်ခွင့်မပြုပေ';
$Definition['ErrorRecordNotFound'] = 'The requested record could not be found.';
$Definition['ErrorTermsOfService'] = 'You must agree to the terms of service.';

$Definition['Female'] = 'မိန်းကလေး';
$Definition['Forgot?'] = 'မေ့နေလား?';

$Definition['Gender'] = 'ကျား ၊ မ';
$Definition['GenderSuffix.First.f'] = '';
$Definition['GenderSuffix.First.m'] = '';
$Definition['GenderSuffix.Third.f'] = '';
$Definition['GenderSuffix.Third.m'] = '';
$Definition['Go'] = 'Go';
$Definition['GuestModule.Message'] = 'ကြိုဆိုပါတယ်။ အခုမှ ပထမဆုံး အကြိမ် ရောက်ဖူးတာလား ? ဝင်ရောက် ဆွေးနွေး မေးမြန်းလိုလျှင် အောက်မှာ ရှိတဲ့ button တွေကနေ တဆင့် ဝင်ရောက် ဆွေးနွေးနိုင်သလို အဖွဲ့ ဝင် အသစ်အနေနဲ့လည်း လျှောက်ထားနိုင်ပါတယ်။ ';

$Definition['he'] = 'သူ';
$Definition['her'] = 'သူမ၏';
$Definition['his'] = 'သူ၏';
$Definition['Howdy, Stranger!'] = 'မင်္ဂလာပါ!';

$Definition['I agree to the <a id="TermsOfService" class="Popup" target="terms" href="%s">terms of service</a>'] = 'I agree to the <a id="TermsOfService" class="Popup" target="terms" href="%s">terms of service</a>';
$Definition['I remember now!'] = 'I remember now!';
$Definition['In this Conversation'] = 'ဒီ သီးသန့်စာထဲတွင်';
$Definition['Inbox'] = 'စာတိုက်';
$Definition['Internal'] = 'Internal';
$Definition['Invitation Code'] = 'Invitation Code';
$Definition['Invite'] = 'Invite';
$Definition['Invited by'] = 'Invited by';

$Definition['Joined'] = 'စသည့် နေ့';

$Definition['Keep me signed in'] = 'အမြဲဝင်ထားရန်';

$Definition['Last Active'] = 'နောက်ဆုံး ဝင်ချိန်';
$Definition['Login with Facebook'] = 'Facebook ဖြင့်ဝင်ရန်';

$Definition['Male'] = 'ယောက်ျားလေး';
$Definition['Most recent by %1$s'] = 'နောက်ဆုံးရေးသားသူ %1$s';
$Definition['My Bookmarks'] = 'ကျွနု်ပ် မှတ်ထားမှု';
$Definition['My Discussions'] = 'ကျွနု်ပ်၏ ဆွေးနွေးချက်များ';
$Definition['My Drafts'] = 'ကျွနု်ပ်၏ စာကြမ်း';
$Definition['My Invitations'] = 'ကျွနု်ပ်၏ ဖိတ်ကြားမှုများ';
$Definition['My Preferences'] = 'ကျွန်ုပ်၏ စိတ်ကြိုက် ပြင်ဆင်မှု';

$Definition['Name Unavailable'] = 'Name Unavailable';
$Definition['No discussions were found.'] = 'ဆွေးနွေးချက်များ ရှာမတွေ့ပါ';
$Definition['Notifications'] = 'အချက်ပေး ချက်များ';
$Definition['Notify me of private messages.'] = 'စာရောက်နေရလျှင် အချက်ပေးပါ။';
$Definition['Notify me when I am added to private conversations.'] = 'သီးသန့် အပြန်အလှန် ပြောဆိုမှု ရောက်လာလျှင် အချက်ပေးပါ။';
$Definition['Notify me when people comment on my bookmarked discussions.'] = 'ကျွနု်ပ် မှတ်ထားမှု တွင် မှတ်ချက် ရှိလျှင် အချက်ပေးပါ။';
$Definition['Notify me when people comment on my discussions.'] = 'ကျွန်ုပ်ဆွေးနွေးချက်တွင် တွင် ပြန်လည် မှတ်ချက် ရေးပါက အချက်ပေးပါ။';
$Definition['Notify me when people mention me in comments.'] = 'မှတ်ချက်များတွင် ကျွန်ုပ်အား ရည်ညွှန်းထားလျှင် အချက်ပေးပါ။';
$Definition['Notify me when people mention me in discussion titles.'] = 'ဆွေးနွေးချက်တွင် ကျွန်ုပ်အား ရည်ညွှန်းထားလျှင် အချက်ပေးပါ။';
$Definition['Notify me when people reply to my wall comments.'] = 'ကွျန်ုပ် ကိုယ်ပိုင်မျက်နှာစာတွင် မှာ အခြားသူတွေ မှတ်ချက်ရေးထားခဲ့လျှင် အချက်ပေးပါ။';
$Definition['Notify me when people write on my wall.'] = 'ကွျန်ုပ် ကိုယ်ပိုင် မျက်နှာစာတွင် အခြားသူတွေ လာရေးရင် အချက်ပေးပါ။';

$Definition['Okay'] = 'ကောင်းပြီ';
$Definition['On'] = 'On';
$Definition['Options'] = 'Options';
$Definition['Or you can...'] = 'ဒါမှမဟုတ် သင့်အနေနဲ့ ...';
$Definition['Original'] = 'Original';

$Definition['PageDetailsMessage'] = '%1$s to %2$s';
$Definition['PageDetailsMessageFull'] = '%1$s to %2$s of %3$s';
$Definition['Password'] = 'Password';
$Definition['PasswordRequest'] = 'မင်္ဂလာပါ %1$s,

Someone has requested to reset your password at %2$s. To reset your password, follow this link:

  %3$s

If you did not make this request, disregard this email.';
$Definition['Passwords don\'t match'] = 'Passwords don\'t match';
$Definition['Permalink'] = 'Permalink';
$Definition['Please wait while you are redirected. If you are not redirected, click <a href="%s">here</a>.'] = 'Please wait while you are redirected. If you are not redirected, click <a href="%s">here</a>.';
$Definition['Post Comment'] = 'မှတ်ချက် တင်သည်';
$Definition['Post Discussion'] = 'ဆွေးနွေးချက် တင်သည်';
$Definition['Powered by Vanilla'] = 'Powered by Vanilla';
$Definition['Preview'] = 'နမူနာ';
$Definition['Profile Picture'] = 'Profile Picture';

$Definition['Recent Activity'] = 'ပြီးခဲ့တဲ့ လှုပ်ရှားမှုတွေ';
$Definition['Recipients'] = 'လက်ခံသူများ';
$Definition['Redirecting...'] = 'Redirecting...';
$Definition['Remember me on this computer'] = 'ယခု ကွန်ပြူတာတွေ မှတ်သားထားပါ';
$Definition['Remove My Picture'] = 'ကွျန်ုပ်ပုံကို ဖြုတ်လိုက်ပါ';
$Definition['Request a new password'] = 'လျို့ဝှက်စာလုံး အသစ် တောင်းရန်';
$Definition['Roles'] = 'ကဏ္ဍ';

$Definition['Save'] = 'သိမ်းရန်';
$Definition['Save Draft'] = 'စာကြမ်း သိမ်းရန်';
$Definition['Save Preferences'] = 'Save Preferences';
$Definition['Search'] = 'Search';
$Definition['Select an image on your computer (2mb max)'] = 'Select an image on your computer (2mb max)';
$Definition['Send %s a Message'] = '%s ကို စာပို့ရန်';
$Definition['Send Message'] = 'စာပို့ရန်';
$Definition['Sent To'] = 'သို့';
$Definition['Share'] = 'မျှဝေသည်';
$Definition['she'] = 'she';
$Definition['Sign In'] = 'ဝင်ရန်';
$Definition['Sign In with Google'] = 'Google ဖြင့် ဝင်ရန်';
$Definition['Sign In with OpenID'] = 'OpenID ဖြင့် ဝင်ရန်';
$Definition['Sign In with Twitter'] = 'Twitter ဖြင့်ဝင်ရန်';
$Definition['Sign Out'] = 'ထွက်မည်';
$Definition['Sign Up'] = 'Sign Up';
$Definition['Sink'] = 'Sink';
$Definition['somebody'] = 'somebody';
$Definition['Start a New Conversation'] = 'သီးသန့်စာ အသစ် ရေးရန်';
$Definition['Start a New Discussion'] = 'မေးမြန်း ၊ ဆွေးနွေး မှုစတင်ရန်';
$Definition['Start Conversation'] = 'Start Conversation';
$Definition['Started by %1$s'] = 'Started by %1$s';
$Definition['Status'] = 'Status';

$Definition['Thank You!'] = 'ကျေးဇူးတင်ပါတယ်!';
$Definition['Thumbnail'] = 'ပုံသေး';
$Definition['Transport error: %s'] = 'A fatal error occurred while processing the request.<br />The server returned the following response: %s';

$Definition['Unbookmark'] = 'Unbookmark';
$Definition['Upload'] = 'Upload';
$Definition['Username'] = 'အသုံးပြုသူ နာမည်';

$Definition['ValidateBoolean'] = '%s is not a valid boolean.';
$Definition['ValidateConnection'] = 'The connection parameters you specified failed to open a connection to the database. The database reported the following error: <code>%s</code>';
$Definition['ValidateDate'] = '%s is not a valid date.';
$Definition['ValidateDecimal'] = '%s is not a valid decimal.';
$Definition['ValidateEmail'] = '%s does not appear to be valid.';
$Definition['ValidateEnum'] = '%s is not valid.';
$Definition['ValidateInteger'] = '%s is not a valid integer.';
$Definition['ValidateLength'] = '%1$s is %2$s characters too long.';
$Definition['ValidateMatch'] = 'The %s fields do not match.';
$Definition['ValidateMinimumAge'] = 'You must be at least 16 years old to proceed.';
$Definition['ValidateOneOrMoreArrayItemRequired'] = 'You must select at least one %s.';
$Definition['ValidateRegex'] = '%s does not appear to be in the correct format.';
$Definition['ValidateRequired'] = '%s is required.';
$Definition['ValidateRequiredArray'] = 'You must select at least one %s.';
$Definition['ValidateTime'] = '%s is not a valid time.';
$Definition['ValidateTimestamp'] = '%s is not a valid timestamp.';
$Definition['ValidateUsername'] = 'Usernames must be 3-20 characters and consist of letters, numbers, and underscores.';
$Definition['ValidateVersion'] = 'The %s field is not a valid version number. See the php version_compare() function for examples of valid version numbers.';
$Definition['Visits'] = 'ကြည့်ရှုမှုပေါင်း';

$Definition['wall'] = 'wall';
$Definition['Why do you want to join?'] = 'သင်ဘာကြောင့် ချိတ်ဆက်ချင်တာလဲ ?';
$Definition['Write a comment'] = 'မှတ်ချက်ရေးရန်';
$Definition['Write Comment'] = 'မှတ်ချက်ရေးရန်';
$Definition['Write something about yourself...'] = 'သင့်အကြောင်း တစ်စုံတစ်ခုပေါ့...';

$Definition['you'] = 'သင်';
$Definition['You'] = 'သင်';
$Definition['You already have an account here.'] = 'သင်၏ ​အကောင့် ရှိပြီးသားဖြစ်သည်';
$Definition['You are connected as %s through %s.'] = 'You are connected as %s through %s.';
$Definition['You do not have any conversations.'] = 'You do not have any conversations.';
$Definition['You do not have any notifications yet.'] = 'You do not have any notifications yet.';
$Definition['your'] = 'your';
$Definition['Your application will be reviewed by an administrator. You will be notified by email if your application is approved.'] = 'Your application will be reviewed by an administrator. You will be notified by email if your application is approved.';
$Definition['Your registered username: <strong>%s</strong>'] = 'Your registered username: <strong>%s</strong>';
$Definition['Popular']='လူကြည့်အများဆုံး';
$Definition['Popular Tags']='အသုံးများသည့် Tags';
$Definition['Votes']='ထောက်ခံမှု';
$Definition['Views']='ကြည့်ရှုမှု';

$Definition['Mark All Viewed']='အကုန်ဖတ်ပြီး';
$Definition['More']='ထပ်ပြီးတော့';

/*******
end user
*******/
?>
